### ISSUE TITLE
如何设置组件的高度?

### ISSUE THREAD

**Issue by simeon49** [twp0217/ngx-echarts#11]
**html**
`
<echarts-ng2 class="line-chart" [option]="lineChartOption"></echarts-ng2>
`

**scss**
`
.line-chart {
      flex-basis: 666px;
      flex-grow: 1;
      flex-shrink: 1;
      border-left: 1px solid $BorderColor;
      echarts-ng2 {
        height: 280px !important;
      }
      canvas {
        height: 280px !important;
      }
    }
`

这样的设置没有任何效果,请问该如何设置?

**Comment by twp0217** [comment]
`<echarts-ng2 [option]="option" [style]="{'width': '800px', 'height': '600px'}"></echarts-ng2>`
这样设置即可
