### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by shao37142** [twp0217/ngx-echarts#12]
我在原先的cli里面npm install 了那两项,再启动就会出现
ERROR in multi script-loader!./src/npm:echarts-ng2/bundles/echarts-ng2.umd.min.js
Module not found: Error: Can't resolve 'F:\test\lite-version\src\npm:echarts-ng2\bundles\echarts-ng2.umd.min.js' in 'F:\test\lite-version'
 @ multi script-loader!./src/npm:echarts-ng2/bundles/echarts-ng2.umd.min.js

ERROR in ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'xmlhttprequest' in 'F:\test\lite-version\node_modules\jquery\lib'
 @ ./~/jquery/lib/node-jquery.js 8:28-53
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4321 ./src/main.ts
这样类似的问题...
在没有安装之前是好的

**Comment by twp0217** [comment]
安装完之后你怎么引入的？

**Comment by shao37142** [comment]
在package.json同级目录下新建了一个system.js,然后map添加配置

**Comment by twp0217** [comment]
能给我下你`package.json`内容吗
