### ISSUE TITLE
this.chart为空的问题

### ISSUE THREAD

**Issue by DennisDeng920525** [twp0217/ngx-echarts#14]
我在浏览器的resize事件中加了ng2-echart的resize事件，在浏览器中移动的时候ng2-echart的resize事件有生效，但是确报了Cannot read property 'resize' of null at EchartsNg2Component.resize。 内部的this.chart为null，不知道是什么原因。
![image](https://user-images.githubusercontent.com/28853489/29203112-d0864e66-7ea0-11e7-8918-fa9964725f79.png)
![image](https://user-images.githubusercontent.com/28853489/29203125-ed88daa6-7ea0-11e7-99fa-b42e283b9bbd.png)

**Comment by twp0217** [comment]
我这测试时正常的，能给我下你调用的ts文件吗

**Comment by DennisDeng920525** [comment]
[hr-chart.component.txt](https://github.com/twp0217/echarts-ng2/files/1217123/hr-chart.component.txt)
单独只有一个tab页的时候不会有这个问题，但是我切换tab页回到之前的echart实例页面后会有这个问题。

**Comment by twp0217** [comment]
你用的是什么tab组件

**Comment by DennisDeng920525** [comment]
bootstrap的tabs

**Comment by twp0217** [comment]
你用的是 https://github.com/ng-bootstrap/ng-bootstrap 的tab？

**Comment by DennisDeng920525** [comment]
http://valor-software.com/ngx-bootstrap/#/   用的这个下面的
import { TabsModule } from 'ngx-bootstrap/tabs'

**Comment by twp0217** [comment]
你代码
![image](https://user-images.githubusercontent.com/26423963/29205084-4a892588-7ead-11e7-844b-1d0614c47bce.png)

要先判断echarts是否存在

```
//屏幕自适应
window.addEventListener('resize', function () {
  if(self && self.echarts){
    self.echarts.resize();
  }
})
```

**Comment by DennisDeng920525** [comment]
这个之前我就有判断了 不行的。self.echarts都是存在的 但是进入到echarts-ng2.components.ts后this.chart为null.
![image](https://user-images.githubusercontent.com/28853489/29205325-af4ceab2-7eae-11e7-992c-0fd61c188106.png)

**Comment by twp0217** [comment]
你页面有使用 *ngIf 吗？

**Comment by DennisDeng920525** [comment]
有试过*ngIf="option" 也没用。 不知道你是指这么不？

**Comment by twp0217** [comment]
不是，可以把工程发来看下吗？
无法重现你的问题，我也试了tab，但是是正常的

**Comment by DennisDeng920525** [comment]
工程不是很方便发， 你能把你试过的tab项目发给我看下吗？

**Comment by twp0217** [comment]
你直播把demo
![image](https://user-images.githubusercontent.com/26423963/29208336-398b748e-7ebc-11e7-956a-3e6d48fab505.png)
这个写进去，试下是否正常，demo的tab和你用的是一样的

**Comment by DennisDeng920525** [comment]
这个问题解决了  是window.addEventListener引起的 改成宿主执行就可以了
![image](https://user-images.githubusercontent.com/28853489/29868890-49b6c326-8db3-11e7-87e8-b9a508e0adb5.png)
