### ISSUE TITLE
如何动态的设置theme？

### ISSUE THREAD

**Issue by ding-kai** [twp0217/ngx-echarts#16]
theme修改后无法动态更新。echart3舍弃了setTheme，官方建议是销毁后重建实例，所以建议提供一个reset方法

**Comment by twp0217** [comment]
感谢建议，晚点更新上库

**Comment by twp0217** [comment]
请使用最新版本，设置theme属性即可
`<ngx-echarts [option]="option" [theme]="theme"></ngx-echarts>`
