### ISSUE TITLE
网页自适应的问题

### ISSUE THREAD

**Issue by HEHEMonster** [twp0217/ngx-echarts#18]
echart不能根据网页大小改变大小，我查看了官网的demo是可以的

**Comment by twp0217** [comment]
请参照 https://github.com/twp0217/echarts-ng2/issues/14#issuecomment-325953901 的方法

![image](https://user-images.githubusercontent.com/28853489/29868890-49b6c326-8db3-11e7-87e8-b9a508e0adb5.png)

**Comment by HEHEMonster** [comment]
Thanks,问题照您的方法解决了^_^
