### ISSUE TITLE
初始化优化建议

### ISSUE THREAD

**Issue by tao-zhi-1992** [twp0217/ngx-echarts#2]
因为在 echarts.js 的实现里面，使用了 `setTimeout` ，被 `zone.js` 包装了的 `setTimeout`  会频繁触发 `docheck` 的钩子，如果应用中有组件实现了该生命周期的钩子，将会不断触发，导致性能下降。

可以用 `NgZone` 提供的 `runOutsideAngular` 方法优化:
```javascript
constructor(private zone: NgZone) {}
....
this.zone.runOutsideAngular(() => {
    this.chart = echarts.init(this.host.nativeElement, this.theme, this.style ? {}:this.opts);
 });
```

**Comment by twp0217** [comment]
感谢建议，晚点更新上库
