### ISSUE TITLE
flex布局eCharts初始化显示不正常

### ISSUE THREAD

**Issue by jialeiplush** [twp0217/ngx-echarts#20]
![c pcik2evp6 dx nn78o](https://user-images.githubusercontent.com/25969326/30902338-78b2fbd6-a39d-11e7-80f0-ba88735831d3.png)
这是两幅图 用flex布局 一个占50% 当触发resize的时候就会恢复正常 但是初始化加载的时候就会这个样子，这是我的代码：
![rw j85mcjs 1p_8c8 fh](https://user-images.githubusercontent.com/25969326/30902416-c2415c02-a39d-11e7-9d1d-52e1efb39467.png)
而且初始化时这里的大小也不一样：
![ltnd i 07p 49vwc4 y3q0](https://user-images.githubusercontent.com/25969326/30902602-5e7ccdb8-a39e-11e7-8559-019d348dd50e.png)

**Comment by jialeiplush** [comment]
另外 当有tab的时候 无法获取宽高 有什么方案可以解决这些问题吗

**Comment by twp0217** [comment]
可以在tab显示的时候触发下 `resize` 事件

**Comment by twp0217** [comment]
或者你可以设置生成的图表宽度和高度

**Comment by jialeiplush** [comment]
因为做的响应式布局 我无法指定他的容器宽高，没有什么办法可以让我在初始化的时候让图表去自适应容器宽高吗

**Comment by twp0217** [comment]
能给个demo让我测试下吗
