### ISSUE TITLE
如何使用Echarts 全局对象？

### ISSUE THREAD

**Issue by SkillUsing** [twp0217/ngx-echarts#23]
我需要 echarts.number.parseDate(params.value[0]); 类似这样的操作

http://echarts.baidu.com/demo.html#calendar-pie   这是网页

**Comment by SkillUsing** [comment]
@wzy156917847 您试试：


 
```
@Component({
    selector: '[echart]',
    template: `
<echarts-ng2 class="main" #echarts></echarts-ng2>
`
})
export class EchartComponent
{
@ViewChild('echarts') public echarts: ECharts;
}
```

**Comment by wzy156917847** [comment]
我试了 好像没有把全局的echarts对象封装到里面 谢谢

**Comment by twp0217** [comment]
@wzy156917847 你什么样的全局对象，做什么的

**Comment by wzy156917847** [comment]
就是初始化echarts时候用的对象
![image](https://user-images.githubusercontent.com/33411433/38918718-1f578b32-4321-11e8-9522-56a5c5c04aad.png)

**Comment by twp0217** [comment]
那你应该可以自己导入
`
import * as echarts from 'echarts';`

**Comment by SkillUsing** [comment]
但是页面大小是硬伤啊

**Comment by twp0217** [comment]
@SkillUsing 说明下具体情况

**Comment by wzy156917847** [comment]
@twp0217 可以的 谢谢
