### ISSUE TITLE
showLoading样式无效

### ISSUE THREAD

**Issue by MrPlume2** [twp0217/ngx-echarts#34]
showLoading样式无效 ，看了源码是因为调用echarts api的showloading的时候， 没有传入参数。希望更新，谢谢。

**Comment by twp0217** [comment]
好的，周末整理下

**Comment by twp0217** [comment]
请使用最新版本，设置loading属性即可
`<ngx-echarts [option]="option" [loading]="loading"></ngx-echarts>`
