### ISSUE TITLE
Ionic4 是否无法使用？

### ISSUE THREAD

**Issue by ionicview** [twp0217/ngx-echarts#35]
我创建了Ionic4的一个新工程，似乎图形无法显示。
又创建了一个Ionic3的新工程，图形正常显示了。
Ionic4是无法使用ngx-echarts吗？

**Comment by twp0217** [comment]
我看了下，应该是Ionic4的布局方式导致echarts获取到的宽度为0，因此没有显示。
你可以设置下`[autoResize]="true"`，让echarts自动调整，还有也可以通过设置`initOpts`中的宽度

**Comment by ionicview** [comment]
非常感谢，好用了。
