### ISSUE TITLE
设置style属性时，echarts.init()导致无法正常获取this.host.nativeElement的宽度和高度

### ISSUE THREAD

**Issue by ortizyc** [twp0217/ngx-echarts#6]
eg:

```
<div>
    <echarts-ng2 #echartsNg2 [option]="_option" [style]="{'height':400,'width':500}"></echarts-ng2>
    <div class="title_panel-div">
        ...
    </div>
</div>
```
此时，`echarts-ng2`组件无法正常渲染，组件内部输出`this.style`值正常，但是输出`this.host.nativeElement`发现宽度和高度值并未绑定上去。
此处建议将echarts.init()方法做出修改：
`this.chart = echarts.init(this.host.nativeElement, this.theme, this.style?{}:this.opts);`
改成
`this.chart = echarts.init(this.host.nativeElement, this.theme, Object.assign({},this.opts,this.style));`

**Comment by twp0217** [comment]
`style`请这样设置
`[style]="{'width': '400px', 'height': '500px'}"`
这样可以让获取的高度和宽度和设置的一样
