### ISSUE TITLE
Error: (systemJS)XHR error (404 not found) loading http://localhost:3000/echarts-ng2

### ISSUE THREAD

**Issue by EliechCai** [twp0217/ngx-echarts#7]
我用的是angular的quickstart，按照readme的步骤在app.module.ts里 添加了
` import { EchartsNg2Module } from 'echarts-ng2' `
并且添加在了imports里
然后控制台就报了这个错误
` Error: (systemJS)XHR error (404 not found) loading http://localhost:3000/echarts-ng2 `
不知道是不是在别的地方还需要配置些什么？

**Comment by twp0217** [comment]
你可以Clone项目到本地。进入demo查看例子，目前没生成单个文件

你也可以稍等，周末我重新弄下，到时候弄个systemJS配置的例子

**Comment by EliechCai** [comment]
谢谢，已经解决了
