### ISSUE TITLE
Map china not exists

### ISSUE THREAD

**Issue by 01428984** [twp0217/ngx-echarts#8]
我想用echars的地图功能，一直报找不到map china ... 求帮助，望解决！

**Comment by twp0217** [comment]
请问你导入地图的JSON文件了吗？

**Comment by 01428984** [comment]
就是不知道怎么引入。。。

**Comment by twp0217** [comment]
`import "echarts/map/js/china.js";`

在使用的TS文件内导入地图JS文件

**Comment by 01428984** [comment]
GET，可以了，谢谢，搞了很久！！
