### ISSUE TITLE
Jhipster项目中如何使用导入echarts图啊，急！求解答，谢谢！

### ISSUE THREAD

**Issue by pppzhou** [twp0217/ngx-echarts#9]
请问，我用Jhipster建的项目，前端是基于angular2的，想在项目中导入echarts图，echart和angular2-echarts都安装了，在package.json文件下的dependencies也看到了echarts和angular2-echarts和对应版本，angular-cli.json中也导入了echarts.js，但是项目跑起来后一直报echarts的错误，ReferenceError: echarts is not defined这个错误，意思就是说导入echarts失败吧，具体怎么操作啊。谢谢

- 

- [ ] 1.

**Comment by twp0217** [comment]
angular-cli.json中无需导入

**Comment by twp0217** [comment]
请按照 [README.md](https://github.com/twp0217/echarts-ng2#使用) 的方法实验下，有问题可以提出
